spring:
  application:
    name: sc-order
server:
  port: 8082
user:
  getUserById:
    url: http://sc-user/user/getById/
#management.security.enabled=false
#management.port=8888
#management.context-path=/monitor
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
#=======================================================================
#   Eureka≈‰÷√
#=======================================================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
#=======================================================================
#   MySQL ˝æ›ø‚≈‰÷√
#=======================================================================
#spring.datasource.url=jdbc:mysql://localhost:3306/spring?useSSL=true&useUnicode=true&characterEncoding=utf8
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#=======================================================================
#   Ribbon≈‰÷√
#=======================================================================
#sc-user.ribbon.NFLoadBalancerRuleClassName=com.netflix.loadbalancer.RandomRule
#sc-user.ribbon.listOfServers=localhost:9091,localhost:9092
#=======================================================================
#   Feign≈‰÷√
#=======================================================================
#feign.hystrix.enabled=true
#√¸¡Ó÷¥––≥¨ ± ±º‰,ƒ¨»œ1000ms
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=20000
