spring:
  application:
    name: sc-gateway-zuul
server:
  port: 8084
#=======================================================================
#   Eureka配置
#=======================================================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

