spring:
  application:
    name: sc-gateway-zuul-fallback
server:
  port: 8088
zuul:
  PreRequestLogFilter:
    pre:
      disable: false
#  ignored-services: sc-user
#=======================================================================
#   Eureka配置
#=======================================================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

